version: '3.9'

services:
  nginx:
    build: .
    restart: always
    environment:
      - CERTBOT_EMAIL=florian.berchtold@gmail.com
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - /var/www/html/:/var/www/html/:ro
  php:
    image: php:7-fpm
    restart: always
    volumes:
      - /var/www/html/:/var/www/html/:ro
volumes:
  nginx_secrets:
